name: Test 2 winget'ed wget

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-winget-wget:
    strategy:
      matrix:
        os: [ windows-latest ]

      fail-fast: false

    runs-on: ${{ matrix.os }}
    env:
      JOB_VAR: "job_value"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set up dependencies Windows
        if: runner.os == 'Windows'
        uses: Cyberboss/install-winget@v1          

      - name: set up dependencies Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          winget install -e --id=GNU.Wget2 --accept-source-agreements --accept-package-agreements
          winget list Wget
          winget show Wget
          dir $env:LOCALAPPDATA\Microsoft\WinGet\Packages
          dir $env:LOCALAPPDATA\Microsoft\WinGet\Packages\GNU.Wget2_Microsoft.Winget.Source_8wekyb3d8bbwe
          dir $env:LOCALAPPDATA\Microsoft\WinGet\Packages\GNU.Wget2_Microsoft.Winget.Source_8wekyb3d8bbwe\bin
          where wget2
          $env:Path += ";$env:LOCALAPPDATA\Microsoft\WinGet\Packages\GNU.Wget2_Microsoft.Winget.Source_8wekyb3d8bbwe\";
          where wget2
          wget2
