name: Test winget'ed wget

on:
  workflow_dispatch:
  push:
    branches:
      - feature/update-external-libraries
      - main


jobs:
  test-winget-wget:
    strategy:
      matrix:
        os: [ windows-latest ]

      fail-fast: false

    runs-on: ${{ matrix.os }}
    env:
      JOB_VAR: "job_value"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up dependencies Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y wget cmake autoconf automake

      - name: Set up dependencies Macos
        if: runner.os == 'macOS'
        run: |
          brew install wget cmake autoconf automake

      - name: set up dependencies Windows
        if: runner.os == 'Windows'
        uses: Cyberboss/install-winget@v1          

      - name: set up dependencies Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          winget install -e --id=GNU.Wget2
          rem tree \
          rem tree C:\
          dir C:\Users\aaron\AppData\Local\Microsoft\WinGet\Packages\JernejSimoncic.Wget_Microsoft.Winget.Source_8wekyb3d8bbwe
          $env:Path += ";C:\Users\aaron\AppData\Local\Microsoft\WinGet\Packages\JernejSimoncic.Wget_Microsoft.Winget.Source_8wekyb3d8bbwe\bin\";
          wget
